### ISSUE TITLE
add api for a few notification sounds played via the earable

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/open-earable#22]

**Comment by TobiasRoeddiger** [comment]
- MESSAGE
- SUCCESS
- ERROR
- ALARM

**Comment by TobiasRoeddiger** [comment]
![image](https://github.com/OpenEarable/open-earable/assets/11386075/7c0f4239-cfcc-4e22-a09f-80ad3f505518)

**Comment by TobiasRoeddiger** [comment]
@kuettner97 I have created an initial list of sounds and ids. @ilteen is currently preparing the sound files.

**Comment by ilteen** [comment]
[jingles.zip](https://github.com/OpenEarable/open-earable/files/12813862/jingles.zip)
