### ISSUE TITLE
how do we encode the button state as sensor?

### ISSUE THREAD

**Issue by TobiasRoeddiger** [OpenEarable/open-earable#35]
read 1 = pressed, read 0 = released
onPress notify 1, onRelease notify 0

**Comment by TobiasRoeddiger** [comment]
if necessary, debounce in software

**Comment by kuettner97** [comment]
> read 1 = pressed, read 0 = released
> onPress notify 1, onRelease notify 0

maybe state, timestamp last press, timestamp last release
