### ISSUE TITLE
Open wearable board cannot be detected by laptop and Arduino IDE

### ISSUE THREAD

**Issue by Oscar-Chung-CKL** [OpenEarable/open-earable#76]
Hello, I am trying to use Arduino IDE to upload some new sketch to the open wearable board via Arduino IDE. However, when I try to connect the open wearable board via a USB cable and use Arduino IDE to upload the sketch, I found out that the board cannot be detected and not shown on Arduino IDE when choosing the port. The board is not shown on device manager either. Does anyone have ideas on solving such issue ? Thanks a lot.

Remarks: I followed the Arduino IDE set up steps shown in the repo already and it still does not work

**Comment by TobiasRoeddiger** [comment]
Hello, You have to flash the bootloader first. Also see this issue: https://github.com/OpenEarable/open-earable/issues/75
