### ISSUE TITLE
burning the bootloader

### ISSUE THREAD

**Issue by Oscar-Chung-CKL** [OpenEarable/open-earable#79]
Hello, I am trying to burn the bootloader to the OpenEarable board. But I could not burn it using a JLink programmer. I followed the instructions from segger (https://wiki.segger.com/Arduino_Nano_33_BLE). 

Since the pin layout of the OpenEarable is different from the Segger, I am using the following connection instead:
OpenEarable SCL pin - SWCLK (pin 9)
OpenEarable SDA pin - SWDIO (pin 7)
VCC - VCC
GND - GND

I used the connection above to try to burn the bootloader to the OpenEarable, but the JLink programmer cannot detect anything at all. I was using the JLink commander and assume the device as default (NRF52840_XXAA). And I tried to connect to the device using SWD and JTAG, which none of them worked.

May I know if my burning steps are correct or I should use another connection / setting ? Thank you.

**Comment by TobiasRoeddiger** [comment]
Please use the pads on the backside of the PCB (under the battery). There you will find 3V3, GND SWCLK, and SWDIO.

SCL and SDA are the I2C pins which are unrelated to the bootloader flashing.
